version: '3.8'
services:
  apache:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:80
    volumes:
      - .:/var/www/html

  mysql:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=0000
      - MYSQL_DATABASE=test_db
      - MYSQL_USER=ruslan
      - MYSQL_PASSWORD=0000

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - 8080:80
    environment:
      - PMA_HOST=mysql
      - MYSQL_ROOT_PASSWORD=0000
